// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package stores is a generated GoMock package.
package stores

import (
	context "context"
	reflect "reflect"
	models "threelayer/models"

	gomock "github.com/golang/mock/gomock"
)

// MockStudentStorer is a mock of StudentStorer interface.
type MockStudentStorer struct {
	ctrl     *gomock.Controller
	recorder *MockStudentStorerMockRecorder
}

// MockStudentStorerMockRecorder is the mock recorder for MockStudentStorer.
type MockStudentStorerMockRecorder struct {
	mock *MockStudentStorer
}

// NewMockStudentStorer creates a new mock instance.
func NewMockStudentStorer(ctrl *gomock.Controller) *MockStudentStorer {
	mock := &MockStudentStorer{ctrl: ctrl}
	mock.recorder = &MockStudentStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentStorer) EXPECT() *MockStudentStorerMockRecorder {
	return m.recorder
}

// GetStudentById mocks base method.
func (m *MockStudentStorer) GetStudentById(arg0 context.Context, arg1 int) (*models.Students, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudentById", arg0, arg1)
	ret0, _ := ret[0].(*models.Students)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudentById indicates an expected call of GetStudentById.
func (mr *MockStudentStorerMockRecorder) GetStudentById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudentById", reflect.TypeOf((*MockStudentStorer)(nil).GetStudentById), arg0, arg1)
}

// GetStudents mocks base method.
func (m *MockStudentStorer) GetStudents(arg0 context.Context) ([]models.Students, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStudents", arg0)
	ret0, _ := ret[0].([]models.Students)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStudents indicates an expected call of GetStudents.
func (mr *MockStudentStorerMockRecorder) GetStudents(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStudents", reflect.TypeOf((*MockStudentStorer)(nil).GetStudents), arg0)
}

// PostStudent mocks base method.
func (m *MockStudentStorer) PostStudent(arg0 context.Context, arg1 models.StudentReq) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostStudent", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostStudent indicates an expected call of PostStudent.
func (mr *MockStudentStorerMockRecorder) PostStudent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostStudent", reflect.TypeOf((*MockStudentStorer)(nil).PostStudent), arg0, arg1)
}
